# Generated by Django 4.0.2 on 2022-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
