# Generated by Django 4.0.2 on 2022-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization_code',
            field=models.CharField(blank=True, default='xxxx', max_length=4, null=True),
        ),
    ]
