# Generated by Django 4.0.2 on 2022-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='self_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
